/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         /app/src/SOLARCOST.cbl */
/* Generated at           Nov 04 2025 23:11:19 */
/* GnuCOBOL build date    Sep 19 2022 00:25:48 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -A -fprofile-arcs -ftest-coverage -Q -lgcov -save-temps -o /app/bin/SOLARCOST /app/src/SOLARCOST.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/app/src/SOLARCOST.cbl"
#define  COB_PACKAGE_VERSION		"4.0-early-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Nov 04 2025 23:11:19"
#define  COB_MODULE_DATE		20251104
#define  COB_MODULE_TIME		231119

/* Global variables */
#include "SOLARCOST.c.h"

/* Function prototypes */

static int		SOLARCOST ();
static int		SOLARCOST_ (const int);
static void		SOLARCOST_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (SOLARCOST ());
}

/* Functions */

/* PROGRAM-ID 'SOLARCOST' */

/* ENTRY 'SOLARCOST' */

static int
SOLARCOST ()
{
  return SOLARCOST_ (0);
}

static int
SOLARCOST_ (const int entry)
{
  /* Program local variables */
  #include "SOLARCOST.c.l.h"

  /* Entry point name_hash values */
  static const unsigned int st_name_hash [] = {
  	0x26B4AB88,	/* SOLARCOST */
  0};
  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, st_name_hash))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (3, &d0, &d1, &d2);

  /* Increment module active */
  module->module_active++;

  /* Save number of call params */
  module->module_num_params = cob_glob_ptr->cob_call_params;

  goto l_2;
  cob_glob_ptr->cob_call_params = 0;

  /* PROCEDURE DIVISION */

  /* Line: 123       : Entry     SOLARCOST               : /app/src/SOLARCOST.cbl */
  l_2:;

  /* Line: 127       : Paragraph 000-MAIN-CONTROL        : /app/src/SOLARCOST.cbl */
  /* Line: 128       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 100-INITIALIZE-PROGRAM */
  frame_ptr++;
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_22;
  goto l_5;
  l_22:
  frame_ptr--;
  /* Line: 129       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 200-PROCESS-CSV-FILE */
  frame_ptr++;
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_6;
  l_23:
  frame_ptr--;
  /* Line: 130       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 300-CALCULATE-COSTS */
  frame_ptr++;
  frame_ptr->perform_through = 10;
  frame_ptr->return_address_ptr = &&l_24;
  goto l_10;
  l_24:
  frame_ptr--;
  /* Line: 131       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 400-GENERATE-REPORT */
  frame_ptr++;
  frame_ptr->perform_through = 14;
  frame_ptr->return_address_ptr = &&l_25;
  goto l_14;
  l_25:
  frame_ptr--;
  /* Line: 132       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 900-CLEANUP-AND-EXIT */
  frame_ptr++;
  frame_ptr->perform_through = 21;
  frame_ptr->return_address_ptr = &&l_26;
  goto l_21;
  l_26:
  frame_ptr--;
  /* Line: 133       : STOP RUN           : /app/src/SOLARCOST.cbl */
  cob_stop_run (b_2);

  /* Line: 138       : Paragraph 100-INITIALIZE-PROGRAM  : /app/src/SOLARCOST.cbl */
  l_5:;
  /* Line: 139       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 1, &c_3);
  /* Line: 141       : ACCEPT             : /app/src/SOLARCOST.cbl */
  cob_get_environment ((cob_field *)&c_4, &f_12);
  /* Line: 142       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp (&f_12, &cob_all_space) == 0))
  {
    /* Line: 143       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_5, &f_12);
  }
  /* Line: 146       : ACCEPT             : /app/src/SOLARCOST.cbl */
  cob_get_environment ((cob_field *)&c_6, &f_13);
  /* Line: 147       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp (&f_13, &cob_all_space) == 0))
  {
    /* Line: 148       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_7, &f_13);
  }
  /* Line: 151       : OPEN               : /app/src/SOLARCOST.cbl */
  cob_open (h_CSV_INPUT_FILE, 1, 0, &f_14);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_1;
    l_27:
    frame_ptr--;
  }
  /* Line: 152       : IF                 : /app/src/SOLARCOST.cbl */
  if (!((int)memcmp (b_14, (cob_u8_ptr)"00", 2) == 0))
  {
    /* Line: 153       : DISPLAY            : /app/src/SOLARCOST.cbl */
    cob_display (0, 1, 2, &c_8, &f_12);
    /* Line: 154       : DISPLAY            : /app/src/SOLARCOST.cbl */
    cob_display (0, 1, 2, &c_9, &f_14);
    /* Line: 155       : STOP RUN           : /app/src/SOLARCOST.cbl */
    cob_stop_run (b_2);
  }
  /* Line: 158       : OPEN               : /app/src/SOLARCOST.cbl */
  cob_open (h_REPORT_OUTPUT_FILE, 2, 0, &f_17);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_1;
    l_28:
    frame_ptr--;
  }
  /* Line: 159       : IF                 : /app/src/SOLARCOST.cbl */
  if (!((int)memcmp (b_14, (cob_u8_ptr)"00", 2) == 0))
  {
    /* Line: 160       : DISPLAY            : /app/src/SOLARCOST.cbl */
    cob_display (0, 1, 2, &c_10, &f_13);
    /* Line: 161       : DISPLAY            : /app/src/SOLARCOST.cbl */
    cob_display (0, 1, 2, &c_9, &f_17);
    /* Line: 162       : STOP RUN           : /app/src/SOLARCOST.cbl */
    cob_stop_run (b_2);
  }
  /* Line: 165       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 2, &c_11, &f_12);
  /* Line: 166       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 2, &c_12, &f_13);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 171       : Paragraph 200-PROCESS-CSV-FILE    : /app/src/SOLARCOST.cbl */
  l_6:;
  /* Line: 172       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 1, &c_13);
  /* Line: 173       : PERFORM            : /app/src/SOLARCOST.cbl */
  for (;;)
  {
    if (((int)memcmp (b_14, (cob_u8_ptr)"10", 2) == 0))
      break;
    /* Line: 174       : PERFORM            : /app/src/SOLARCOST.cbl */
    /* PERFORM 210-READ-CSV-RECORD */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_7;
    l_29:
    frame_ptr--;
    /* Line: 175       : IF                 : /app/src/SOLARCOST.cbl */
    if (!((int)memcmp (b_14, (cob_u8_ptr)"10", 2) == 0))
    {
      /* Line: 176       : IF                 : /app/src/SOLARCOST.cbl */
      if (((int)(int)(*(b_19) - 89) == 0))
      {
        /* Line: 177       : MOVE               : /app/src/SOLARCOST.cbl */
        *(b_19) = 78;
        /* Line: 178       : DISPLAY            : /app/src/SOLARCOST.cbl */
        cob_display (0, 1, 1, &c_14);
      }
      else
      {
        /* ELSE */
        /* Line: 180       : PERFORM            : /app/src/SOLARCOST.cbl */
        /* PERFORM 220-PARSE-CSV-FIELDS */
        frame_ptr++;
        frame_ptr->perform_through = 8;
        frame_ptr->return_address_ptr = &&l_30;
        goto l_8;
        l_30:
        frame_ptr--;
        /* Line: 181       : PERFORM            : /app/src/SOLARCOST.cbl */
        /* PERFORM 230-ACCUMULATE-TOTALS */
        frame_ptr++;
        frame_ptr->perform_through = 9;
        frame_ptr->return_address_ptr = &&l_31;
        goto l_9;
        l_31:
        frame_ptr--;
        /* Line: 182       : ADD                : /app/src/SOLARCOST.cbl */
        cob_set_llint (&f_18, 100000LL, (cob_s64_t)(cob_get_numdisp (b_18, 5) + 1));
      }
    }
  }
  /* Line: 187       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 3, &c_15, &f_18, &c_16);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 192       : Paragraph 210-READ-CSV-RECORD     : /app/src/SOLARCOST.cbl */
  l_7:;
  /* Line: 193       : READ               : /app/src/SOLARCOST.cbl */
  cob_read_next (h_CSV_INPUT_FILE, &f_14, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {
      /* Line: 195       : SET                : /app/src/SOLARCOST.cbl */
      memcpy (b_14, "10", 2);
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_32;
      goto l_1;
      l_32:
      frame_ptr--;
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 201       : Paragraph 220-PARSE-CSV-FIELDS    : /app/src/SOLARCOST.cbl */
  l_8:;
  /* Line: 202       : UNSTRING           : /app/src/SOLARCOST.cbl */
  cob_unstring_init (&f_8, NULL, 1);
  cob_unstring_delimited ((cob_field *)&c_17, 0);
  cob_unstring_into (&f_23, 0, 0);
  cob_unstring_into (&f_24, 0, 0);
  cob_unstring_into (&f_25, 0, 0);
  cob_unstring_into (&f_26, 0, 0);
  cob_unstring_into (&f_27, 0, 0);
  cob_unstring_into (&f_28, 0, 0);
  cob_unstring_into (&f_29, 0, 0);
  cob_unstring_into (&f_30, 0, 0);
  cob_unstring_into (&f_31, 0, 0);
  cob_unstring_into (&f_32, 0, 0);
  cob_unstring_into (&f_33, 0, 0);
  cob_unstring_into (&f_34, 0, 0);
  cob_unstring_into (&f_35, 0, 0);
  cob_unstring_into (&f_36, 0, 0);
  cob_unstring_into (&f_37, 0, 0);
  cob_unstring_finish ();

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 224       : Paragraph 230-ACCUMULATE-TOTALS   : /app/src/SOLARCOST.cbl */
  l_9:;
  /* Line: 226       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp (&f_25, &cob_all_space) != 0))
  {
    /* Line: 227       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move (cob_intr_numval (&f_25), &f_38);
    /* Line: 228       : ADD                : /app/src/SOLARCOST.cbl */
    cob_add (&f_40, &f_38, 0);
  }
  /* Line: 232       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp (&f_26, &cob_all_space) != 0))
  {
    /* Line: 233       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move (cob_intr_numval (&f_26), &f_39);
    /* Line: 235       : ADD                : /app/src/SOLARCOST.cbl */
    cob_add (&f_41, &f_39, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 241       : Paragraph 300-CALCULATE-COSTS     : /app/src/SOLARCOST.cbl */
  l_10:;
  /* Line: 242       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 1, &c_18);
  /* Line: 244       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 310-CONVERT-TO-KWH */
  frame_ptr++;
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_33;
  goto l_11;
  l_33:
  frame_ptr--;
  /* Line: 245       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 320-CALCULATE-FINANCIALS */
  frame_ptr++;
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_34;
  goto l_12;
  l_34:
  frame_ptr--;
  /* Line: 246       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 330-COMPUTE-PROJECTIONS */
  frame_ptr++;
  frame_ptr->perform_through = 13;
  frame_ptr->return_address_ptr = &&l_35;
  goto l_13;
  l_35:
  frame_ptr--;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 251       : Paragraph 310-CONVERT-TO-KWH      : /app/src/SOLARCOST.cbl */
  l_11:;
  /* Line: 253       : COMPUTE            : /app/src/SOLARCOST.cbl */
  cob_decimal_set_field (d0, &f_40);
  cob_decimal_div (d0, dc_1);
  cob_decimal_get_field (d0, &f_43, 0);
  /* Line: 254       : COMPUTE            : /app/src/SOLARCOST.cbl */
  cob_decimal_set_field (d0, &f_41);
  cob_decimal_div (d0, dc_1);
  cob_decimal_get_field (d0, &f_44, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 260       : Paragraph 320-CALCULATE-FINANCIALS: /app/src/SOLARCOST.cbl */
  l_12:;
  /* Line: 262       : COMPUTE            : /app/src/SOLARCOST.cbl */
  cob_decimal_set_field (d0, &f_43);
  cob_decimal_set_field (d1, &f_42);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_45, 0);
  /* Line: 266       : COMPUTE            : /app/src/SOLARCOST.cbl */
  cob_decimal_set_field (d0, &f_44);
  cob_decimal_set_field (d1, &f_42);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_46, 0);
  /* Line: 270       : COMPUTE            : /app/src/SOLARCOST.cbl */
  cob_decimal_set_field (d0, &f_45);
  cob_decimal_set_field (d1, &f_46);
  cob_decimal_sub (d0, d1);
  cob_decimal_get_field (d0, &f_47, 0);
  /* Line: 274       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp_llint (&f_44, 0LL) > 0))
  {
    /* Line: 275       : COMPUTE            : /app/src/SOLARCOST.cbl */
    cob_decimal_set_field (d0, &f_43);
    cob_decimal_set_field (d1, &f_44);
    cob_decimal_div (d0, d1);
    cob_decimal_mul (d0, dc_2);
    cob_decimal_get_field (d0, &f_48, 0);
  }
  else
  {
    /* ELSE */
    /* Line: 279       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_set_packed_zero (&f_48);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 285       : Paragraph 330-COMPUTE-PROJECTIONS : /app/src/SOLARCOST.cbl */
  l_13:;
  /* Line: 287       : IF                 : /app/src/SOLARCOST.cbl */
  if ( (cob_get_numdisp (b_18, 5) > 0) )
  {
    /* Line: 288       : COMPUTE            : /app/src/SOLARCOST.cbl */
    cob_decimal_set_field (d0, &f_43);
    cob_decimal_set_field (d1, &f_18);
    cob_decimal_div (d0, d1);
    cob_decimal_get_field (d0, &f_49, 0);
    /* Line: 290       : COMPUTE            : /app/src/SOLARCOST.cbl */
    cob_decimal_set_field (d0, &f_44);
    cob_decimal_set_field (d1, &f_18);
    cob_decimal_div (d0, d1);
    cob_decimal_get_field (d0, &f_50, 0);
    /* Line: 294       : COMPUTE            : /app/src/SOLARCOST.cbl */
    cob_decimal_set_field (d0, &f_47);
    cob_decimal_set_llint (d1, 365LL);
    cob_decimal_set_field (d2, &f_18);
    cob_decimal_div (d1, d2);
    cob_decimal_mul (d0, d1);
    cob_decimal_get_field (d0, &f_51, 0);
    /* Line: 298       : IF                 : /app/src/SOLARCOST.cbl */
    if (((int)cob_cmp_llint (&f_51, 0LL) > 0))
    {
      /* Line: 299       : COMPUTE            : /app/src/SOLARCOST.cbl */
      cob_decimal_set_llint (d0, 1000LL);
      cob_decimal_set_field (d1, &f_51);
      cob_decimal_div (d0, d1);
      cob_decimal_get_field (d0, &f_59, 0);
      /* Line: 301       : COMPUTE            : /app/src/SOLARCOST.cbl */
      cob_decimal_set_llint (d0, 2000LL);
      cob_decimal_set_field (d1, &f_51);
      cob_decimal_div (d0, d1);
      cob_decimal_get_field (d0, &f_60, 0);
      /* Line: 303       : COMPUTE            : /app/src/SOLARCOST.cbl */
      cob_decimal_set_llint (d0, 3000LL);
      cob_decimal_set_field (d1, &f_51);
      cob_decimal_div (d0, d1);
      cob_decimal_get_field (d0, &f_61, 0);
    }
    else
    {
      /* ELSE */
      /* Line: 306       : MOVE               : /app/src/SOLARCOST.cbl */
      cob_move ((cob_field *)&c_19, &f_59);
      /* Line: 307       : MOVE               : /app/src/SOLARCOST.cbl */
      cob_move ((cob_field *)&c_19, &f_60);
      /* Line: 308       : MOVE               : /app/src/SOLARCOST.cbl */
      cob_move ((cob_field *)&c_19, &f_61);
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 315       : Paragraph 400-GENERATE-REPORT     : /app/src/SOLARCOST.cbl */
  l_14:;
  /* Line: 316       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 1, &c_20);
  /* Line: 318       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 410-PRINT-HEADER */
  frame_ptr++;
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_36;
  goto l_15;
  l_36:
  frame_ptr--;
  /* Line: 319       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 420-PRINT-ENERGY-SUMMARY */
  frame_ptr++;
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_37;
  goto l_16;
  l_37:
  frame_ptr--;
  /* Line: 320       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 430-PRINT-FINANCIAL-ANALYSIS */
  frame_ptr++;
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_38;
  goto l_17;
  l_38:
  frame_ptr--;
  /* Line: 321       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 440-PRINT-PROJECTIONS */
  frame_ptr++;
  frame_ptr->perform_through = 18;
  frame_ptr->return_address_ptr = &&l_39;
  goto l_18;
  l_39:
  frame_ptr--;
  /* Line: 322       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 450-PRINT-INVESTMENT-GUIDANCE */
  frame_ptr++;
  frame_ptr->perform_through = 19;
  frame_ptr->return_address_ptr = &&l_40;
  goto l_19;
  l_40:
  frame_ptr--;
  /* Line: 323       : PERFORM            : /app/src/SOLARCOST.cbl */
  /* PERFORM 460-PRINT-FOOTER */
  frame_ptr++;
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_41;
  goto l_20;
  l_41:
  frame_ptr--;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 328       : Paragraph 410-PRINT-HEADER        : /app/src/SOLARCOST.cbl */
  l_15:;
  /* Line: 329       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62 + 70, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_42;
    goto l_1;
    l_42:
    frame_ptr--;
  }
  /* Line: 330       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_21, &f_10);
  /* Line: 331       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_43;
    goto l_1;
    l_43:
    frame_ptr--;
  }
  /* Line: 332       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62 + 70, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_44;
    goto l_1;
    l_44:
    frame_ptr--;
  }
  /* Line: 333       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_45;
    goto l_1;
    l_45:
    frame_ptr--;
  }
  /* Line: 336       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 337       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_18, &f_57);
  /* Line: 338       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_22);
  cob_string_delimited (NULL);
  cob_string_append (&f_57);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_23);
  cob_string_finish ();
  /* Line: 342       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_46;
    goto l_1;
    l_46:
    frame_ptr--;
  }
  /* Line: 345       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_24, &f_10);
  /* Line: 346       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_47;
    goto l_1;
    l_47:
    frame_ptr--;
  }
  /* Line: 347       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_48;
    goto l_1;
    l_48:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 352       : Paragraph 420-PRINT-ENERGY-SUMMARY: /app/src/SOLARCOST.cbl */
  l_16:;
  /* Line: 353       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_49;
    goto l_1;
    l_49:
    frame_ptr--;
  }
  /* Line: 354       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_25, &f_10);
  /* Line: 355       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_50;
    goto l_1;
    l_50:
    frame_ptr--;
  }
  /* Line: 356       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_51;
    goto l_1;
    l_51:
    frame_ptr--;
  }
  /* Line: 359       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 360       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_43, &f_52);
  /* Line: 361       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_26);
  cob_string_delimited (NULL);
  cob_string_append (&f_52);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_27);
  cob_string_finish ();
  /* Line: 365       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_52;
    goto l_1;
    l_52:
    frame_ptr--;
  }
  /* Line: 368       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 369       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_44, &f_52);
  /* Line: 370       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_28);
  cob_string_delimited (NULL);
  cob_string_append (&f_52);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_27);
  cob_string_finish ();
  /* Line: 374       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_53;
    goto l_1;
    l_53:
    frame_ptr--;
  }
  /* Line: 377       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 378       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_48, &f_56);
  /* Line: 379       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_29);
  cob_string_delimited (NULL);
  cob_string_append (&f_56);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_30);
  cob_string_finish ();
  /* Line: 383       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_54;
    goto l_1;
    l_54:
    frame_ptr--;
  }
  /* Line: 384       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_55;
    goto l_1;
    l_55:
    frame_ptr--;
  }
  /* Line: 387       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 388       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_49, &f_53);
  /* Line: 389       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_31);
  cob_string_delimited (NULL);
  cob_string_append (&f_53);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_27);
  cob_string_finish ();
  /* Line: 393       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_56;
    goto l_1;
    l_56:
    frame_ptr--;
  }
  /* Line: 396       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 397       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_50, &f_53);
  /* Line: 398       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_32);
  cob_string_delimited (NULL);
  cob_string_append (&f_53);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_27);
  cob_string_finish ();
  /* Line: 402       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_57;
    goto l_1;
    l_57:
    frame_ptr--;
  }
  /* Line: 403       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_58;
    goto l_1;
    l_58:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 408       : Paragraph 430-PRINT-FINANCIAL-ANALYSIS: /app/src/SOLARCOST.cbl */
  l_17:;
  /* Line: 409       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_59;
    goto l_1;
    l_59:
    frame_ptr--;
  }
  /* Line: 410       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_33, &f_10);
  /* Line: 411       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_60;
    goto l_1;
    l_60:
    frame_ptr--;
  }
  /* Line: 412       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_61;
    goto l_1;
    l_61:
    frame_ptr--;
  }
  /* Line: 415       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 416       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_45, &f_55);
  /* Line: 417       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_34);
  cob_string_delimited (NULL);
  cob_string_append (&f_55);
  cob_string_finish ();
  /* Line: 420       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_62;
    goto l_1;
    l_62:
    frame_ptr--;
  }
  /* Line: 423       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 424       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_46, &f_55);
  /* Line: 425       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_35);
  cob_string_delimited (NULL);
  cob_string_append (&f_55);
  cob_string_finish ();
  /* Line: 428       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_63;
    goto l_1;
    l_63:
    frame_ptr--;
  }
  /* Line: 431       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 432       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_47, &f_55);
  /* Line: 433       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_36);
  cob_string_delimited (NULL);
  cob_string_append (&f_55);
  cob_string_finish ();
  /* Line: 436       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_64;
    goto l_1;
    l_64:
    frame_ptr--;
  }
  /* Line: 437       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_65;
    goto l_1;
    l_65:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Line: 442       : Paragraph 440-PRINT-PROJECTIONS   : /app/src/SOLARCOST.cbl */
  l_18:;
  /* Line: 443       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_66;
    goto l_1;
    l_66:
    frame_ptr--;
  }
  /* Line: 444       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_37, &f_10);
  /* Line: 445       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_67;
    goto l_1;
    l_67:
    frame_ptr--;
  }
  /* Line: 446       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_68;
    goto l_1;
    l_68:
    frame_ptr--;
  }
  /* Line: 449       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 450       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_51, &f_55);
  /* Line: 451       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_38);
  cob_string_delimited (NULL);
  cob_string_append (&f_55);
  cob_string_finish ();
  /* Line: 454       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_69;
    goto l_1;
    l_69:
    frame_ptr--;
  }
  /* Line: 455       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_70;
    goto l_1;
    l_70:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 460       : Paragraph 450-PRINT-INVESTMENT-GUIDANCE: /app/src/SOLARCOST.cbl */
  l_19:;
  /* Line: 461       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_71;
    goto l_1;
    l_71:
    frame_ptr--;
  }
  /* Line: 462       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_39, &f_10);
  /* Line: 463       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_72;
    goto l_1;
    l_72:
    frame_ptr--;
  }
  /* Line: 464       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_73;
    goto l_1;
    l_73:
    frame_ptr--;
  }
  /* Line: 467       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 468       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_18, &f_57);
  /* Line: 469       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_40);
  cob_string_delimited (NULL);
  cob_string_append (&f_57);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_41);
  cob_string_finish ();
  /* Line: 473       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_74;
    goto l_1;
    l_74:
    frame_ptr--;
  }
  /* Line: 474       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_75;
    goto l_1;
    l_75:
    frame_ptr--;
  }
  /* Line: 477       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 478       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_45, &f_55);
  /* Line: 479       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_42);
  cob_string_delimited (NULL);
  cob_string_append (&f_55);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_43);
  cob_string_finish ();
  /* Line: 483       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_76;
    goto l_1;
    l_76:
    frame_ptr--;
  }
  /* Line: 486       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp_llint (&f_47, 0LL) > 0))
  {
    /* Line: 487       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_44, &f_10);
  }
  else
  {
    /* ELSE */
    /* Line: 490       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_45, &f_10);
  }
  /* Line: 493       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_77;
    goto l_1;
    l_77:
    frame_ptr--;
  }
  /* Line: 496       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 497       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_48, &f_56);
  /* Line: 498       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_46);
  cob_string_delimited (NULL);
  cob_string_append (&f_56);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_47);
  cob_string_finish ();
  /* Line: 502       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_78;
    goto l_1;
    l_78:
    frame_ptr--;
  }
  /* Line: 503       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_79;
    goto l_1;
    l_79:
    frame_ptr--;
  }
  /* Line: 506       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_48, &f_10);
  /* Line: 507       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_80;
    goto l_1;
    l_80:
    frame_ptr--;
  }
  /* Line: 509       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 510       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_51, &f_55);
  /* Line: 511       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_49);
  cob_string_delimited (NULL);
  cob_string_append (&f_55);
  cob_string_finish ();
  /* Line: 514       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_81;
    goto l_1;
    l_81:
    frame_ptr--;
  }
  /* Line: 516       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move ((cob_field *)&c_50, &f_10);
  /* Line: 518       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_82;
    goto l_1;
    l_82:
    frame_ptr--;
  }
  /* Line: 521       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 522       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_59, &f_58);
  /* Line: 523       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_51);
  cob_string_delimited (NULL);
  cob_string_append (&f_58);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_52);
  cob_string_finish ();
  /* Line: 527       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_83;
    goto l_1;
    l_83:
    frame_ptr--;
  }
  /* Line: 529       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 530       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_60, &f_58);
  /* Line: 531       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_53);
  cob_string_delimited (NULL);
  cob_string_append (&f_58);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_52);
  cob_string_finish ();
  /* Line: 535       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_84;
    goto l_1;
    l_84:
    frame_ptr--;
  }
  /* Line: 537       : MOVE               : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  /* Line: 538       : MOVE               : /app/src/SOLARCOST.cbl */
  cob_move (&f_61, &f_58);
  /* Line: 539       : STRING             : /app/src/SOLARCOST.cbl */
  cob_string_init (&f_10, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_54);
  cob_string_delimited (NULL);
  cob_string_append (&f_58);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_52);
  cob_string_finish ();
  /* Line: 543       : WRITE              : /app/src/SOLARCOST.cbl */
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_85;
    goto l_1;
    l_85:
    frame_ptr--;
  }
  /* Line: 544       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_86;
    goto l_1;
    l_86:
    frame_ptr--;
  }
  /* Line: 547       : IF                 : /app/src/SOLARCOST.cbl */
  if (((int)cob_cmp (&f_49, (cob_field *)&c_55) < 0))
  {
    /* Line: 548       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_56, &f_10);
    /* Line: 550       : WRITE              : /app/src/SOLARCOST.cbl */
    cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_87;
      goto l_1;
      l_87:
      frame_ptr--;
    }
    /* Line: 551       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_57, &f_10);
    /* Line: 553       : WRITE              : /app/src/SOLARCOST.cbl */
    cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_88;
      goto l_1;
      l_88:
      frame_ptr--;
    }
    /* Line: 554       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_58, &f_10);
    /* Line: 556       : WRITE              : /app/src/SOLARCOST.cbl */
    cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_89;
      goto l_1;
      l_89:
      frame_ptr--;
    }
  }
  else
  {
    /* ELSE */
    /* Line: 558       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_59, &f_10);
    /* Line: 560       : WRITE              : /app/src/SOLARCOST.cbl */
    cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_90;
      goto l_1;
      l_90:
      frame_ptr--;
    }
    /* Line: 561       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_60, &f_10);
    /* Line: 563       : WRITE              : /app/src/SOLARCOST.cbl */
    cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_91;
      goto l_1;
      l_91:
      frame_ptr--;
    }
    /* Line: 564       : MOVE               : /app/src/SOLARCOST.cbl */
    cob_move ((cob_field *)&c_61, &f_10);
    /* Line: 566       : WRITE              : /app/src/SOLARCOST.cbl */
    cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_92;
      goto l_1;
      l_92:
      frame_ptr--;
    }
  }
  /* Line: 568       : WRITE              : /app/src/SOLARCOST.cbl */
  memset (b_11, 32, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_93;
    goto l_1;
    l_93:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Line: 573       : Paragraph 460-PRINT-FOOTER        : /app/src/SOLARCOST.cbl */
  l_20:;
  /* Line: 574       : WRITE              : /app/src/SOLARCOST.cbl */
  memcpy (b_11, b_62 + 70, 70);
  cob_write (h_REPORT_OUTPUT_FILE, &f_10, 2162689, &f_17, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_94;
    goto l_1;
    l_94:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 20)
    goto *frame_ptr->return_address_ptr;

  /* Line: 579       : Paragraph 900-CLEANUP-AND-EXIT    : /app/src/SOLARCOST.cbl */
  l_21:;
  /* Line: 580       : CLOSE              : /app/src/SOLARCOST.cbl */
  cob_close (h_CSV_INPUT_FILE, &f_14, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_95;
    goto l_1;
    l_95:
    frame_ptr--;
  }
  /* Line: 581       : CLOSE              : /app/src/SOLARCOST.cbl */
  cob_close (h_REPORT_OUTPUT_FILE, &f_17, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_96;
    goto l_1;
    l_96:
    frame_ptr--;
  }
  /* Line: 582       : DISPLAY            : /app/src/SOLARCOST.cbl */
  cob_display (0, 1, 1, &c_62);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 21)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : /app/src/SOLARCOST.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
      goto l_1;
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  SOLARCOST_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  cob_set_llint (COB_SET_FLD(f0, 4, (cob_u8_t *)&b_2, &a_21), 1000000000LL, (cob_s64_t)0);
  memset (b_12, 32, 100);
  memset (b_13, 32, 100);
  memset (b_14, 32, 2);
  memset (b_17, 32, 2);
  memset (b_18, 48, 5);
  *(cob_u8_ptr)(b_19) = 89;
  memset (b_22, 32, 150);
  cob_set_packed_zero (&f_38);
  cob_set_packed_zero (&f_39);
  cob_set_packed_zero (&f_40);
  cob_set_packed_zero (&f_41);
  cob_move ((cob_field *)&c_63, &f_42);
  cob_set_packed_zero (&f_43);
  cob_set_packed_zero (&f_44);
  cob_set_packed_zero (&f_45);
  cob_set_packed_zero (&f_46);
  cob_set_packed_zero (&f_47);
  cob_set_packed_zero (&f_48);
  cob_set_packed_zero (&f_49);
  cob_set_packed_zero (&f_50);
  cob_set_packed_zero (&f_51);
  cob_move (&cob_all_zero, &f_52);
  cob_move (&cob_all_zero, &f_53);
  cob_move (&cob_all_zero, COB_SET_FLD(f0, 11, b_54, &a_23));
  cob_move (&cob_all_zero, &f_55);
  cob_move (&cob_all_zero, &f_56);
  cob_move (&cob_all_zero, &f_57);
  cob_move (&cob_all_zero, &f_58);
  cob_set_packed_zero (&f_59);
  cob_set_packed_zero (&f_60);
  cob_set_packed_zero (&f_61);
  memset (b_62, 45, 70);
  memset (b_62 + 70, 61, 70);

  /* File initialization for CSV-INPUT-FILE */
  cob_file_create (&h_CSV_INPUT_FILE, NULL, "CSV-INPUT-FILE",
                   COB_ORG_LINE_SEQUENTIAL,COB_ACCESS_SEQUENTIAL,0,
                   COB_FILE_IS_DFLT,COB_SELECT_FILE_STATUS,0,0,200,
                   &f_12,&f_9);
  cob_file_complete (h_CSV_INPUT_FILE);

  /* File initialization for REPORT-OUTPUT-FILE */
  cob_file_create (&h_REPORT_OUTPUT_FILE, NULL, "REPORT-OUTPUT-FILE",
                   COB_ORG_LINE_SEQUENTIAL,COB_ACCESS_SEQUENTIAL,0,
                   COB_FILE_IS_DFLT,COB_SELECT_FILE_STATUS,0,0,70,
                   &f_13,&f_11);
  cob_file_complete (h_REPORT_OUTPUT_FILE);

  /* Set Decimal Constant values */
  dc_2 = &kc_2;
  cob_decimal_init(dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init(dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear(dc_2);
  dc_2 = NULL;
  cob_decimal_clear(dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'SOLARCOST' */

/* Initialize module structure for SOLARCOST */
static void SOLARCOST_module_init (cob_module *module)
{
  module->module_name = "SOLARCOST";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())SOLARCOST;
  module->module_cancel.funcptr = (void *(*)())SOLARCOST_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

