/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         /app/src/SOLARCOST.cbl */
/* Generated at           Nov 05 2025 04:12:58 */
/* GnuCOBOL build date    Sep 19 2022 00:25:48 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -g -fdebugging-line -A -fprofile-arcs -ftest-coverage -Q -lgcov -save-temps -o /app/bin/SOLARCOST /app/src/SOLARCOST.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 2},
	{'9', 1},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'Z', 3},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};
static const cob_pic_symbol p_3[] = {
	{'Z', 3},
	{'9', 1},
	{'.', 1},
	{'9', 1},
	{'\0', 1}
};
static const cob_pic_symbol p_4[] = {
	{'Z', 1},
	{'9', 1},
	{'.', 1},
	{'9', 3},
	{'\0', 1}
};
static const cob_pic_symbol p_5[] = {
	{'$', 1},
	{'Z', 3},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};
static const cob_pic_symbol p_6[] = {
	{'$', 4},
	{',', 1},
	{'$', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x12,   8,   2, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x12,  10,   2, 0x0000, NULL};
static const cob_field_attr a_8 =	{0x12,   9,   3, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x12,   4,   3, 0x0000, NULL};
static const cob_field_attr a_10 =	{0x12,   7,   2, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x12,   7,   2, 0x0001, NULL};
static const cob_field_attr a_12 =	{0x12,   6,   1, 0x0000, NULL};
static const cob_field_attr a_13 =	{0x12,   7,   3, 0x0000, NULL};
static const cob_field_attr a_14 =	{0x10,   5,   1, 0x1000, NULL};
static const cob_field_attr a_15 =	{0x24,   3,   0, 0x0000, p_1};
static const cob_field_attr a_16 =	{0x24,   6,   2, 0x0000, p_2};
static const cob_field_attr a_17 =	{0x24,   5,   1, 0x0000, p_3};
static const cob_field_attr a_18 =	{0x24,   5,   3, 0x0000, p_4};
static const cob_field_attr a_19 =	{0x24,   6,   2, 0x0000, p_5};
static const cob_field_attr a_20 =	{0x10,   2,   1, 0x1000, NULL};
static const cob_field_attr a_21 =	{0x11,   9,   0, 0x0001, NULL};
static const cob_field_attr a_22 =	{0x10,   4,   3, 0x1000, NULL};
static const cob_field_attr a_23 =	{0x24,   8,   2, 0x0000, p_6};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {4, (cob_u8_ptr)"1000", &a_1};
static const cob_field c_2	= {3, (cob_u8_ptr)"100", &a_2};
static const cob_field c_3	= {43, (cob_u8_ptr)"Initializing Solar Cost Analysis Program...", &a_3};
static const cob_field c_4	= {9, (cob_u8_ptr)"CSV_INPUT", &a_3};
static const cob_field c_5	= {24, (cob_u8_ptr)"../data/SolarHistory.csv", &a_3};
static const cob_field c_6	= {13, (cob_u8_ptr)"REPORT_OUTPUT", &a_3};
static const cob_field c_7	= {30, (cob_u8_ptr)"./output/solar_cost_report.txt", &a_3};
static const cob_field c_8	= {31, (cob_u8_ptr)"ERROR: Cannot open input file: ", &a_3};
static const cob_field c_9	= {13, (cob_u8_ptr)"File Status: ", &a_3};
static const cob_field c_10	= {32, (cob_u8_ptr)"ERROR: Cannot open output file: ", &a_3};
static const cob_field c_11	= {12, (cob_u8_ptr)"Input file: ", &a_3};
static const cob_field c_12	= {13, (cob_u8_ptr)"Output file: ", &a_3};
static const cob_field c_13	= {25, (cob_u8_ptr)"Processing CSV records...", &a_3};
static const cob_field c_14	= {19, (cob_u8_ptr)"Skipping header row", &a_3};
static const cob_field c_15	= {10, (cob_u8_ptr)"Processed ", &a_3};
static const cob_field c_16	= {13, (cob_u8_ptr)" data records", &a_3};
static const cob_field c_17	= {1, (cob_u8_ptr)",", &a_3};
static const cob_field c_18	= {20, (cob_u8_ptr)"Calculating costs...", &a_3};
static const cob_field c_19	= {5, (cob_u8_ptr)"99999", &a_14};
static const cob_field c_20	= {20, (cob_u8_ptr)"Generating report...", &a_3};
static const cob_field c_21	= {33, (cob_u8_ptr)"SOLAR ENERGY COST ANALYSIS REPORT", &a_3};
static const cob_field c_22	= {17, (cob_u8_ptr)"Analysis Period: ", &a_3};
static const cob_field c_23	= {5, (cob_u8_ptr)" days", &a_3};
static const cob_field c_24	= {32, (cob_u8_ptr)"Electricity Rate: $0.140 per kWh", &a_3};
static const cob_field c_25	= {14, (cob_u8_ptr)"ENERGY SUMMARY", &a_3};
static const cob_field c_26	= {27, (cob_u8_ptr)"Solar Energy Collected:    ", &a_3};
static const cob_field c_27	= {4, (cob_u8_ptr)" kWh", &a_3};
static const cob_field c_28	= {27, (cob_u8_ptr)"Energy Consumed:           ", &a_3};
static const cob_field c_29	= {27, (cob_u8_ptr)"Solar Offset:              ", &a_3};
static const cob_field c_30	= {1, (cob_u8_ptr)"%", &a_3};
static const cob_field c_31	= {27, (cob_u8_ptr)"Daily Average Solar:       ", &a_3};
static const cob_field c_32	= {27, (cob_u8_ptr)"Daily Average Consumption: ", &a_3};
static const cob_field c_33	= {18, (cob_u8_ptr)"FINANCIAL ANALYSIS", &a_3};
static const cob_field c_34	= {27, (cob_u8_ptr)"Value of Solar Generated:  ", &a_3};
static const cob_field c_35	= {27, (cob_u8_ptr)"Cost of Energy Consumed:   ", &a_3};
static const cob_field c_36	= {27, (cob_u8_ptr)"NET SAVINGS:               ", &a_3};
static const cob_field c_37	= {11, (cob_u8_ptr)"PROJECTIONS", &a_3};
static const cob_field c_38	= {27, (cob_u8_ptr)"Projected Annual Savings:  ", &a_3};
static const cob_field c_39	= {19, (cob_u8_ptr)"INVESTMENT GUIDANCE", &a_3};
static const cob_field c_40	= {14, (cob_u8_ptr)"Based on your ", &a_3};
static const cob_field c_41	= {14, (cob_u8_ptr)"-day analysis:", &a_3};
static const cob_field c_42	= {30, (cob_u8_ptr)"* Your solar system generates ", &a_3};
static const cob_field c_43	= {16, (cob_u8_ptr)" worth of energy", &a_3};
static const cob_field c_44	= {50, (cob_u8_ptr)"* You are NET POSITIVE - solar exceeds consumption", &a_3};
static const cob_field c_45	= {42, (cob_u8_ptr)"* You are consuming more than you generate", &a_3};
static const cob_field c_46	= {16, (cob_u8_ptr)"* Solar offsets ", &a_3};
static const cob_field c_47	= {22, (cob_u8_ptr)"% of your energy needs", &a_3};
static const cob_field c_48	= {22, (cob_u8_ptr)"Annual Value Analysis:", &a_3};
static const cob_field c_49	= {33, (cob_u8_ptr)"* Annual solar generation value: ", &a_3};
static const cob_field c_50	= {44, (cob_u8_ptr)"* Break-even timeline depends on system cost", &a_3};
static const cob_field c_51	= {20, (cob_u8_ptr)"  - $1,000 system = ", &a_3};
static const cob_field c_52	= {14, (cob_u8_ptr)" years payback", &a_3};
static const cob_field c_53	= {20, (cob_u8_ptr)"  - $2,000 system = ", &a_3};
static const cob_field c_54	= {20, (cob_u8_ptr)"  - $3,000 system = ", &a_3};
static const cob_field c_55	= {2, (cob_u8_ptr)"05", &a_20};
static const cob_field c_56	= {49, (cob_u8_ptr)"Recommendation: Your current solar output is LOW.", &a_3};
static const cob_field c_57	= {38, (cob_u8_ptr)"Consider expanding your solar array to", &a_3};
static const cob_field c_58	= {40, (cob_u8_ptr)"maximize ROI and reduce grid dependence.", &a_3};
static const cob_field c_59	= {41, (cob_u8_ptr)"Recommendation: Strong solar performance.", &a_3};
static const cob_field c_60	= {37, (cob_u8_ptr)"Current capacity appears adequate for", &a_3};
static const cob_field c_61	= {44, (cob_u8_ptr)"maximizing ROI and reducing grid dependence.", &a_3};
static const cob_field c_62	= {30, (cob_u8_ptr)"Program completed successfully", &a_3};
static const cob_field c_63	= {4, (cob_u8_ptr)"0140", &a_22};

static cob_field cob_all_space	= {1, (cob_u8_ptr)" ", &cob_all_attr};
static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


/* Strings */
static const char st_1[]	= "PERFORM";
static const char st_2[]	= "STOP RUN";
static const char st_3[]	= "DISPLAY";
static const char st_4[]	= "ACCEPT";
static const char st_5[]	= "IF";
static const char st_6[]	= "MOVE";
static const char st_7[]	= "OPEN";
static const char st_8[]	= "ADD";
static const char st_9[]	= "READ";
static const char st_10[]	= "SET";
static const char st_11[]	= "UNSTRING";
static const char st_12[]	= "COMPUTE";
static const char st_13[]	= "WRITE";
static const char st_14[]	= "STRING";
static const char st_15[]	= "CLOSE";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/app/src/SOLARCOST.cbl"};

static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p;
	register int	n;
	register int 	retval = 0;
	p = (const unsigned char *)data;
	for (n = 0; n < size; ++n, ++p) {
		if (*p > '0' && *p <= '9')
	       break;
	}
	for (; n < size; ++n, ++p) {
   	retval = (retval * 10)
   	       + ((*p > '0' && *p <= '9') ? (*p - '0') : 0);
	}
	return retval;
}


/* Decimal constants */
static	cob_decimal	kc_1;
static	cob_decimal	*dc_1 = NULL;
static	cob_decimal	kc_2;
static	cob_decimal	*dc_2 = NULL;

