/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         /app/src/SOLARCOST.cbl */
/* Generated at           Nov 04 2025 23:11:19 */
/* GnuCOBOL build date    Sep 19 2022 00:25:48 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -A -fprofile-arcs -ftest-coverage -Q -lgcov -save-temps -o /app/bin/SOLARCOST /app/src/SOLARCOST.cbl */

/* Program local variables for 'SOLARCOST' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;
cob_decimal	*d1 = NULL;
cob_decimal	*d2 = NULL;


/* File CSV-INPUT-FILE */
static cob_file		*h_CSV_INPUT_FILE = NULL;

/* File REPORT-OUTPUT-FILE */
static cob_file		*h_REPORT_OUTPUT_FILE = NULL;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* WORKING-STORAGE Data */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_9[200] __attribute__((aligned));	/* CSV-INPUT-FILE Record */
static cob_u8_t	b_11[70] __attribute__((aligned));	/* REPORT-OUTPUT-FILE Record */
static cob_u8_t	b_12[100] __attribute__((aligned));	/* CSV-FILE */
static cob_u8_t	b_13[100] __attribute__((aligned));	/* REPORT-FILE */
static cob_u8_t	b_14[2] __attribute__((aligned));	/* WS-FILE-STATUS */
static cob_u8_t	b_17[2] __attribute__((aligned));	/* WS-REPORT-STATUS */
static cob_u8_t	b_18[5] __attribute__((aligned));	/* WS-RECORD-COUNT */
static cob_u8_t	b_19[1] __attribute__((aligned));	/* WS-FIRST-RECORD-FLAG */
static cob_u8_t	b_22[150] __attribute__((aligned));	/* WS-CSV-FIELDS */
static cob_u8_t	b_38[5] __attribute__((aligned));	/* WS-YIELD-WH */
static cob_u8_t	b_39[5] __attribute__((aligned));	/* WS-CONSUMPTION-WH */
static cob_u8_t	b_40[6] __attribute__((aligned));	/* WS-TOTAL-YIELD-WH */
static cob_u8_t	b_41[6] __attribute__((aligned));	/* WS-TOTAL-CONSUMPTION-WH */
static cob_u8_t	b_42[3] __attribute__((aligned));	/* WS-RATE-PER-KWH */
static cob_u8_t	b_43[5] __attribute__((aligned));	/* WS-TOTAL-SOLAR-KWH */
static cob_u8_t	b_44[5] __attribute__((aligned));	/* WS-TOTAL-CONSUMPTION-KWH */
static cob_u8_t	b_45[4] __attribute__((aligned));	/* WS-SOLAR-VALUE-USD */
static cob_u8_t	b_46[4] __attribute__((aligned));	/* WS-CONSUMPTION-COST-USD */
static cob_u8_t	b_47[4] __attribute__((aligned));	/* WS-NET-SAVINGS-USD */
static cob_u8_t	b_48[4] __attribute__((aligned));	/* WS-SOLAR-OFFSET-PCT */
static cob_u8_t	b_49[4] __attribute__((aligned));	/* WS-AVG-DAILY-SOLAR-KWH */
static cob_u8_t	b_50[4] __attribute__((aligned));	/* WS-AVG-DAILY-CONSUMP-KWH */
static cob_u8_t	b_51[5] __attribute__((aligned));	/* WS-PROJECTED-ANNUAL-USD */
static cob_u8_t	b_52[7] __attribute__((aligned));	/* WS-EDIT-KWH-1 */
static cob_u8_t	b_53[6] __attribute__((aligned));	/* WS-EDIT-KWH-2 */
static cob_u8_t	b_54[11] __attribute__((aligned));	/* WS-EDIT-USD */
static cob_u8_t	b_55[8] __attribute__((aligned));	/* WS-EDIT-USD-SMALL */
static cob_u8_t	b_56[6] __attribute__((aligned));	/* WS-EDIT-PCT */
static cob_u8_t	b_57[3] __attribute__((aligned));	/* WS-EDIT-DAYS */
static cob_u8_t	b_58[6] __attribute__((aligned));	/* WS-EDIT-YEARS */
static cob_u8_t	b_59[4] __attribute__((aligned));	/* WS-PAYBACK-1000 */
static cob_u8_t	b_60[4] __attribute__((aligned));	/* WS-PAYBACK-2000 */
static cob_u8_t	b_61[4] __attribute__((aligned));	/* WS-PAYBACK-3000 */
static cob_u8_t	b_62[140] __attribute__((aligned));	/* WS-CONSTANTS */

/* End of WORKING-STORAGE data */


/* Local Fields */
static cob_field f_8	= {200, b_9, &a_4};	/* CSV-RECORD */
static cob_field f_9	= {200, b_9, &a_4};	/* CSV-INPUT-FILE Record */
static cob_field f_10	= {70, b_11, &a_4};	/* REPORT-LINE */
static cob_field f_11	= {70, b_11, &a_4};	/* REPORT-OUTPUT-FILE Record */
static cob_field f_12	= {100, b_12, &a_4};	/* CSV-FILE */
static cob_field f_13	= {100, b_13, &a_4};	/* REPORT-FILE */
static cob_field f_14	= {2, b_14, &a_4};	/* WS-FILE-STATUS */
static cob_field f_17	= {2, b_17, &a_4};	/* WS-REPORT-STATUS */
static cob_field f_18	= {5, b_18, &a_5};	/* WS-RECORD-COUNT */
static cob_field f_23	= {10, b_22, &a_4};	/* WS-DAYS-AGO */
static cob_field f_24	= {10, b_22 + 10, &a_4};	/* WS-DATE-STR */
static cob_field f_25	= {10, b_22 + 20, &a_4};	/* WS-YIELD-STR */
static cob_field f_26	= {10, b_22 + 30, &a_4};	/* WS-CONSUMPTION-STR */
static cob_field f_27	= {10, b_22 + 40, &a_4};	/* WS-MAX-PV-POWER */
static cob_field f_28	= {10, b_22 + 50, &a_4};	/* WS-MAX-PV-VOLTAGE */
static cob_field f_29	= {10, b_22 + 60, &a_4};	/* WS-MIN-BATTERY-V */
static cob_field f_30	= {10, b_22 + 70, &a_4};	/* WS-MAX-BATTERY-V */
static cob_field f_31	= {10, b_22 + 80, &a_4};	/* WS-TIME-BULK */
static cob_field f_32	= {10, b_22 + 90, &a_4};	/* WS-TIME-ABSORPTION */
static cob_field f_33	= {10, b_22 + 100, &a_4};	/* WS-TIME-FLOAT */
static cob_field f_34	= {10, b_22 + 110, &a_4};	/* WS-ERROR-1 */
static cob_field f_35	= {10, b_22 + 120, &a_4};	/* WS-ERROR-2 */
static cob_field f_36	= {10, b_22 + 130, &a_4};	/* WS-ERROR-3 */
static cob_field f_37	= {10, b_22 + 140, &a_4};	/* WS-ERROR-4 */
static cob_field f_38	= {5, b_38, &a_6};	/* WS-YIELD-WH */
static cob_field f_39	= {5, b_39, &a_6};	/* WS-CONSUMPTION-WH */
static cob_field f_40	= {6, b_40, &a_7};	/* WS-TOTAL-YIELD-WH */
static cob_field f_41	= {6, b_41, &a_7};	/* WS-TOTAL-CONSUMPTION-WH */
static cob_field f_42	= {3, b_42, &a_9};	/* WS-RATE-PER-KWH */
static cob_field f_43	= {5, b_43, &a_8};	/* WS-TOTAL-SOLAR-KWH */
static cob_field f_44	= {5, b_44, &a_8};	/* WS-TOTAL-CONSUMPTION-KWH */
static cob_field f_45	= {4, b_45, &a_10};	/* WS-SOLAR-VALUE-USD */
static cob_field f_46	= {4, b_46, &a_10};	/* WS-CONSUMPTION-COST-USD */
static cob_field f_47	= {4, b_47, &a_11};	/* WS-NET-SAVINGS-USD */
static cob_field f_48	= {4, b_48, &a_12};	/* WS-SOLAR-OFFSET-PCT */
static cob_field f_49	= {4, b_49, &a_13};	/* WS-AVG-DAILY-SOLAR-KWH */
static cob_field f_50	= {4, b_50, &a_13};	/* WS-AVG-DAILY-CONSUMP-KWH */
static cob_field f_51	= {5, b_51, &a_6};	/* WS-PROJECTED-ANNUAL-USD */
static cob_field f_52	= {7, b_52, &a_16};	/* WS-EDIT-KWH-1 */
static cob_field f_53	= {6, b_53, &a_18};	/* WS-EDIT-KWH-2 */
static cob_field f_55	= {8, b_55, &a_19};	/* WS-EDIT-USD-SMALL */
static cob_field f_56	= {6, b_56, &a_17};	/* WS-EDIT-PCT */
static cob_field f_57	= {3, b_57, &a_15};	/* WS-EDIT-DAYS */
static cob_field f_58	= {6, b_58, &a_17};	/* WS-EDIT-YEARS */
static cob_field f_59	= {4, b_59, &a_12};	/* WS-PAYBACK-1000 */
static cob_field f_60	= {4, b_60, &a_12};	/* WS-PAYBACK-2000 */
static cob_field f_61	= {4, b_61, &a_12};	/* WS-PAYBACK-3000 */

/* End of fields */

